version: '3'
services: 
  redis:
    container_name: redis-dev    
    ports:
      - 6379:6379
  cli:
    image: redis:7.2.4
    command: redis-cli -h redis
  redisinsight:
    image: redislabs/redisinsight
    ports:
      - 6380:8001
