#!/bin/bash

# while-menu-dialog: a menu driven system information program

# Dialog box color
DIALOG_CANCEL=1
DIALOG_ESC=255
HEIGHT=0
WIDTH=0

options=(1 "ENV_A"
         2 "ENV_B"
         )

while true; do
  exec 3>&1
  selection=$(dialog \
    --backtitle "SSH env" \
    --title "Menu" \
    --clear \
    --cancel-label "Exit" \
    --menu "Please select env:" 22 76 16 \
    "${options[@]}" \
    2>&1 1>&3)
  exit_status=$?
  exec 3>&-
  case $exit_status in
    $DIALOG_CANCEL)
      clear
      echo "Program terminated."
      exit
      ;;
    $DIALOG_ESC)
      clear
      echo "Program aborted." >&2
      exit 1
      ;;    
  esac
  case $selection in
    0 )
      clear
      echo "Program terminated."
      ;;
    1 )
      clear
      ssh user@X.X.X.X
      exit 1
      ;;
    2 )
      clear
      ssh user@X.X.X.X
      exit 1
      ;;   
  esac
done

